### ISSUE TITLE
Need help in skipping cronjob when already scripts for previous cronjob are running

### ISSUE THREAD

**Issue by CodeWithSid675** [wahengchang/nodejs-cron-job-must-know#3]
I have written a cron job as given below

var cron = require('node-cron');
var taskMap = {};
let job = cron.schedule('*/1 * * * * ', ()=>{
var shell = require('./utils/child_helper');

var commandList = [
    "node  *****",
    "node  *****", 
    "node  ******"
]

 shell.series(commandList , function(err,res){
//    console.log('executed many commands in a row');
    console.log('done')
});
});

which need to run on every 1 min but the scripts inside the cron may take more than 1 min.
I need to skip the cron for the moment when the scripts are still running .
Can anyone help me on it.

Calling cron from app.js as below code

const express = require('express');
const app = express();
const bodyParser = require('body-parser');
var port = 3000;
require('./cronController').job.start();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.listen(port , ()=>{
let dateTime = new Date();
let message = 'Server is running on Port :- ' + port + ' started at :- ' + dateTime;
console.log(message);
});

**Comment by wahengchang** [comment]
there are two things that I can think about may help:
#### 1- killing child process 
 - [https://stackoverflow.com/questions/53269578/node-js-process-exit-vs-childprocess-kill](https://stackoverflow.com/questions/53269578/node-js-process-exit-vs-childprocess-kill)
 - [https://solidgeargroup.com/invoking-background-processes-from-nodejs/](https://solidgeargroup.com/invoking-background-processes-from-nodejs/)
```js
const { spawn } = require('child_process');
const grep = spawn('grep', ['ssh']);
grep.on('close', (code, signal) => {
  console.log(
    `child process terminated due to receipt of signal ${signal}`);
});
// Send SIGHUP to process

```

#### 2- wraping your child process as js (promise)
as I see your` commandList` are all  js script, why dont u execute them by JS function ?

changing this to
```js
var commandList = [
"node script1.js",
"node script2.js",
"node script3.js"
]
```

```js
var commandList = [fun1, fun2, fun3]
shell.series(commandList , async function(err,res){
 await fun1()
 await fun2()
 await fun3()
});
```

**Comment by CodeWithSid675** [comment]
Thank you!
